[project]
name = "hornet-finder-api"
version = "0.1.0"
description = "API for a hornet detection app."
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name="Martin Devolder", email="martin.devolder2@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "django==6.1.1",
    "djangorestframework==3.18.1",
    "drf-spectacular[sidecar]==0.30.0",
    "gunicorn==26.2.0",
    "psycopg2-binary==2.9.13",
    "PyJWT==2.13.0",
    "python-keycloak==7.1.1",
    "segno==1.6.6"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
