# Generated by Django 5.2 on 2025-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('destroyed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
