# Generated by Django 5.2.4 on 2025-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0002_add_color_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nest',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]