# Generated by Django 5.2.4 on 2025-07-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0004_apiary_point_hornet_point_nest_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # Ajout de deux utilisateurs stubs pour la migration des FK existantes
        migrations.RunSQL(
            sql="""
            INSERT INTO hornet_user (guid, date_created) VALUES
            ('f0dd2c7d-38b4-4158-9bb6-1a4027b9d4be', NOW()),
            ('c1b9ee64-f3b2-4b99-a776-a9f233b5e291', NOW()),
            ('a197ac6e-e805-43a5-acbe-204286f487ba', NOW()),
            ('d6e6f3c2-fad1-40c4-9a6f-4848d1f514c2', NOW());
            """,
            reverse_sql="""
            DELETE FROM hornet_user WHERE guid IN ('f0dd2c7d-38b4-4158-9bb6-1a4027b9d4be', 'c1b9ee64-f3b2-4b99-a776-a9f233b5e291', 'a197ac6e-e805-43a5-acbe-204286f487ba', 'd6e6f3c2-fad1-40c4-9a6f-4848d1f514c2');
            """
        ),
        migrations.AlterField(
            model_name='apiary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hornet.user'),
        ),
        migrations.AlterField(
            model_name='hornet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hornet.user'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hornet.user'),
        ),
    ]
