# Generated by Django 5.2.4 on 2025-07-30 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0005_user_alter_apiary_created_by_alter_hornet_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeekeeperGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('path', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiaryGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hornet.apiary')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hornet.beekeepergroup')),
            ],
            options={
                'unique_together': {('apiary', 'group')},
            },
        ),
        migrations.AddField(
            model_name='apiary',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='apiaries', through='hornet.ApiaryGroupPermission', to='hornet.beekeepergroup'),
        ),
    ]
