# Generated by Django 6.1.1 on 2026-09-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0006_beekeepergroup_apiarygrouppermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hornet',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hornet',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nest',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
