# Generated by Django 6.1.1 on 2026-09-22 14:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import hornet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0007_hornet_archived_hornet_archived_at_nest_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=128)),
                ('wikipedia_url', models.URLField(blank=True, default='', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=hornet.models.trap_type_photo_path)),
                ('photo_thumbnail', models.ImageField(blank=True, null=True, upload_to=hornet.models.trap_type_photo_path)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group_paths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('group', 'Group only')], default='public', max_length=16)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=hornet.models.trap_photo_path)),
                ('photo_thumbnail', models.ImageField(blank=True, null=True, upload_to=hornet.models.trap_photo_path)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('installed_at', models.DateField()),
                ('comments', models.TextField(blank=True, default='')),
                ('hornet_catch_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traps', to='hornet.beekeepergroup')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traps', to='hornet.user')),
                ('trap_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traps', to='hornet.traptype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrapEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('installation', 'Installation'), ('inspection', 'Inspection'), ('cleaning', 'Cleaning'), ('refill', 'Consumable refill'), ('repair', 'Repair'), ('removal', 'Removal'), ('catch', 'Catch')], max_length=16)),
                ('performed_at', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trap_events', to='hornet.user')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trap_events', to='hornet.species')),
                ('trap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hornet.trap')),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrapPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=hornet.models.trap_event_photo_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=hornet.models.trap_event_photo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hornet.trapevent')),
                ('trap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hornet.trap')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trap_photos', to='hornet.user')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trapevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'catch'), ('quantity__gte', 1), ('species__isnull', False)), models.Q(models.Q(('kind', 'catch'), _negated=True), ('quantity__isnull', True), ('species__isnull', True)), _connector='OR'), name='trapevent_catch_fields'),
        ),
    ]
