# Generated by Django 6.1.1 on 2026-09-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0009_seed_trap_referentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=44, unique=True)),
                ('key_index', models.PositiveSmallIntegerField(db_index=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('associated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('associated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_tags', to='hornet.user')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tags', to='hornet.user')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_tags', to='hornet.user')),
                ('trap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='hornet.trap')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('trap__isnull', False)), fields=('trap',), name='tag_one_active_per_trap')],
            },
        ),
    ]
