# Generated by Django 6.1.1 on 2026-09-23 07:44

import hornet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0010_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=hornet.models.species_photo_path),
        ),
        migrations.AddField(
            model_name='species',
            name='photo_credit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='species',
            name='photo_source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='species',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=hornet.models.species_photo_path),
        ),
        migrations.AddField(
            model_name='trapevent',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
