# Generated by Django 6.1.1 on 2026-09-24 20:22

import hornet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hornet', '0011_species_photo_catch_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=hornet.models.avatar_upload_path),
        ),
    ]
