# Generated by Django 6.1.1 on 2026-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hornet", "0015_traptype_apiary_bound"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trapevent",
            name="trapevent_catch_fields",
        ),
        migrations.AddField(
            model_name="trapevent",
            name="bycatch_counted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="trapevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "catch"),
                        ("quantity__gte", 0),
                        ("species__isnull", False),
                    ),
                    models.Q(
                        models.Q(("kind", "catch"), _negated=True),
                        ("bycatch_counted__isnull", True),
                        ("quantity__isnull", True),
                        ("species__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="trapevent_catch_fields",
            ),
        ),
    ]
