# Generated by Django 6.1.1 on 2026-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hornet", "0016_trapevent_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiary",
            name="infestation_level",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Light"), (2, "Medium"), (3, "High")],
                null=True,
            ),
        ),
    ]
