# Generated by Django 6.1.1 on 2026-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hornet", "0019_group_invitation_reminders"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("statistic", models.CharField(max_length=50)),
                ("params", models.JSONField(default=dict)),
                ("scope", models.JSONField(default=dict)),
                ("summary", models.JSONField(default=list)),
                ("requester", models.CharField(db_index=True, max_length=64)),
                ("requester_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("downloads", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
