# Generated by Django 6.1.1 on 2026-10-08 14:31

import django.db.models.deletion
import hornet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hornet", "0021_trap_accumulation"),
    ]

    operations = [
        migrations.CreateModel(
            name="NestPhoto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to=hornet.models.nest_photo_path)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=hornet.models.nest_photo_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="hornet.nest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nest_photos",
                        to="hornet.user",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
