import api from './api';
import type { AxiosErrorResponse } from './axiosTypes';
import type { Trap } from '../store/slices/trapsSlice';

/**
 * Signed QR tags. The backend checks every scanned value (HMAC signature, then
 * presence in its database) and logs each refusal; the frontend only extracts
 * the value from the scanned URL and routes it to `/tag/<value>`.
 */

/** A tag value: 33 bytes in base64url, i.e. exactly 44 characters. */
const TAG_VALUE = /^[A-Za-z0-9_-]{44}$/;

export interface PrintableTag {
  value: string;
  short: string;
  url: string;
  /** SVG data URI of the QR code, generated by the server */
  qr_svg: string;
  /** Printed under the code of an attached tag, e.g. "Piège #12"; empty when free */
  caption: string;
  generated_at: string | null;
}

export type TagResolution =
  | { status: 'unassociated'; short: string }
  | { status: 'associated'; short: string; trap: Trap };

export interface TagCandidate {
  id: number;
  address: string;
  trap_type: string | null;
  active: boolean;
  has_tag: boolean;
}

/** Error codes returned by the tag endpoints, see `hornet/tag_views.py`. */
export type TagErrorCode =
  | 'invalid' | 'unknown' | 'revoked' | 'forbidden' | 'configuration'
  | 'already_associated' | 'trap_has_tag' | 'not_found' | 'already_revoked' | 'network' | 'error';

export class TagError extends Error {
  constructor(public code: TagErrorCode, message: string, public existingShort?: string) {
    super(message);
  }
}

const MESSAGES: Record<TagErrorCode, string> = {
  invalid: "Ce QR Code n'est pas authentique. L'incident a été enregistré.",
  unknown: "Ce QR Code est inconnu. L'incident a été enregistré.",
  revoked: "Ce QR Code a été révoqué et n'est plus valable.",
  forbidden: "Vous n'avez pas accès au piège de ce QR Code.",
  configuration: "Les QR Codes ne sont pas configurés sur ce serveur.",
  already_associated: 'Ce QR Code est déjà associé à un piège.',
  trap_has_tag: 'Ce piège a déjà un QR Code.',
  not_found: 'Introuvable.',
  already_revoked: 'Ce QR Code est déjà révoqué.',
  network: 'Impossible de joindre le serveur. Réessayez une fois connecté au réseau.',
  error: 'Une erreur est survenue.',
};

function toTagError(error: unknown): TagError {
  const response = (error as AxiosErrorResponse).response;
  const data = response?.data as { code?: TagErrorCode; existing_short?: string } | undefined;
  const fallback: TagErrorCode = response ? 'error' : 'network';
  const code: TagErrorCode = data?.code && data.code in MESSAGES ? data.code : fallback;
  return new TagError(code, MESSAGES[code], data?.existing_short);
}

/**
 * Tag value carried by a scanned text, whatever its host: a tag printed by
 * another site is still sent to the server, which refuses and logs it.
 */
export function extractTagValue(scanned: string): string | null {
  try {
    const url = new URL(scanned.trim());
    const match = /^\/tag\/([^/]+)\/?$/.exec(url.pathname);
    return match && TAG_VALUE.test(match[1]) ? match[1] : null;
  } catch {
    return null;
  }
}

export async function resolveTag(value: string): Promise<TagResolution> {
  try {
    return (await api.get(`/tags/${encodeURIComponent(value)}/`)).data;
  } catch (error) {
    throw toTagError(error);
  }
}

export async function fetchTagCandidates(value: string, query = ''): Promise<TagCandidate[]> {
  try {
    const params = query ? { q: query } : undefined;
    return (await api.get(`/tags/${encodeURIComponent(value)}/candidates/`, { params })).data;
  } catch (error) {
    throw toTagError(error);
  }
}

export async function associateTag(value: string, trapId: number, replace = false): Promise<TagResolution> {
  try {
    return (await api.post(`/tags/${encodeURIComponent(value)}/associate/`, { trap_id: trapId, replace })).data;
  } catch (error) {
    throw toTagError(error);
  }
}

export async function generateTags(count: number): Promise<PrintableTag[]> {
  try {
    return (await api.post('/tags/batch/', { count })).data;
  } catch (error) {
    throw toTagError(error);
  }
}

export async function fetchFreeTags(): Promise<PrintableTag[]> {
  try {
    return (await api.get('/tags/', { params: { unassociated: 1 } })).data;
  } catch (error) {
    throw toTagError(error);
  }
}

/** Tags attached to the caller's own traps, to reprint a lost or damaged label. */
export async function fetchTagsInUse(): Promise<PrintableTag[]> {
  try {
    return (await api.get('/tags/', { params: { associated: 1 } })).data;
  } catch (error) {
    throw toTagError(error);
  }
}

export interface SheetLink {
  /** Opens the PDF without the JWT (signed server-side), valid `expires_in` seconds */
  url: string;
  count: number;
  expires_in: number;
}

/**
 * Link to the A4 PDF of the given tags: the caller's own ones, or any live
 * tag for an admin. A plain link, opened by a real tap, is what works on a
 * phone (an iOS home-screen app ignores window.print and blob downloads).
 */
export async function fetchTagSheetLink(values: string[]): Promise<SheetLink> {
  try {
    return (await api.post('/tags/sheet/', { values })).data;
  } catch (error) {
    throw toTagError(error);
  }
}

// -- administration ----------------------------------------------------------

export type TagStatus = 'free' | 'associated' | 'revoked';

export interface AdminTagUser {
  guid: string;
  display_name: string;
}

export interface AdminTag {
  id: number;
  short: string;
  key_index: number;
  status: TagStatus;
  trap: { id: number; address: string; active: boolean } | null;
  generated_by: AdminTagUser | null;
  generated_at: string | null;
  associated_by: AdminTagUser | null;
  associated_at: string | null;
  revoked_by: AdminTagUser | null;
  revoked_at: string | null;
}

export interface TagKeyUsage {
  index: number;
  /** `retired`: removed from the configuration, its QR Codes no longer verify */
  state: 'active' | 'configured' | 'retired';
  associated: number;
  free: number;
  revoked: number;
}

export interface AdminTagFilters {
  status?: TagStatus | '';
  q?: string;
  key_index?: number | '';
  offset?: number;
}

export async function fetchAdminTags(filters: AdminTagFilters): Promise<{ count: number; results: AdminTag[] }> {
  const params = Object.fromEntries(
    Object.entries(filters).filter(([, value]) => value !== '' && value !== undefined)
  );
  try {
    return (await api.get('/admin/tags/', { params })).data;
  } catch (error) {
    throw toTagError(error);
  }
}

export async function fetchTagKeyUsage(): Promise<TagKeyUsage[]> {
  try {
    return (await api.get('/admin/tags/keys/')).data;
  } catch (error) {
    throw toTagError(error);
  }
}

export async function fetchAdminTagQr(id: number): Promise<PrintableTag> {
  try {
    return (await api.get(`/admin/tags/${id}/qr/`)).data;
  } catch (error) {
    throw toTagError(error);
  }
}

/** Link to the A4 PDF of the tags selected in the administration (revoked ones are skipped). */
export async function fetchAdminTagSheetLink(ids: number[]): Promise<SheetLink> {
  try {
    return (await api.post('/admin/tags/sheet/', { ids })).data;
  } catch (error) {
    throw toTagError(error);
  }
}

export async function revokeTag(id: number): Promise<AdminTag> {
  try {
    return (await api.post(`/admin/tags/${id}/revoke/`)).data;
  } catch (error) {
    throw toTagError(error);
  }
}
