# Generated by Django 6.1.1 on 2026-10-09 19:11

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.utils.timezone
from django.db import migrations, models

# Append-only table: UPDATE always refused, DELETE only inside a transaction
# that set `audit.purge` (the retention purge, audit/recorder.py). Guards
# against bugs and slips, not against someone holding the database owner role.
APPEND_ONLY_SQL = """
CREATE FUNCTION audit_event_append_only() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('audit.purge', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'audit_auditevent is append-only (% refused)', TG_OP;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_event_append_only
    BEFORE UPDATE OR DELETE ON audit_auditevent
    FOR EACH ROW EXECUTE FUNCTION audit_event_append_only();
"""

DROP_APPEND_ONLY_SQL = """
DROP TRIGGER IF EXISTS audit_event_append_only ON audit_auditevent;
DROP FUNCTION IF EXISTS audit_event_append_only();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("actor", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "actor_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("system", "System"),
                            ("backfill", "Rebuilt from existing data"),
                        ],
                        default="api",
                        max_length=16,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("target_type", models.CharField(max_length=32)),
                ("target_id", models.CharField(blank=True, default="", max_length=256)),
                (
                    "target_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "refs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        blank=True,
                        default=list,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("request_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-occurred_at", "-id"], name="audit_occurred_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="audit_target_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["refs"], name="audit_refs_idx"
                    ),
                ],
            },
        ),
        migrations.RunSQL(APPEND_ONLY_SQL, DROP_APPEND_ONLY_SQL),
    ]
